version: "2"

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"

    node-app:
        build:
            context: ./
            args:
                NODE_ENV: production

        environment:
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SESSION_SECRET=${SESSION_SECRET}
        command: node index.js

    mongodb:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

