version: "2"

services:
    node-app:
        build: /.
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
        volumes:
            - mongo-db:/data/db
        depends_on: 
            - mongodb

    mongodb:
        image: mongo

volumes:
    mongo-db: