version: "2"

services:
    node-app:
        build:
            context: ./
            args:
                NODE_ENV: development
        ports:
            - "3000:3000"
        volumes:
            - ./:/app:ro
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=zyzyx
            - MONGO_PASSWORD=mypassword
        command: npm run dev

    mongodb:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=zyzyx
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
    
